In [54]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [105]:
x1 = np.array([0,1,2,3])
x2 = np.array([3,4,1,7])
y = np.array([0,1,0,3])
x1
W=np.array([x1,x2]).T
W

array([[0, 3],
       [1, 4],
       [2, 1],
       [3, 7]])

In [106]:
W= np.insert(W, 0, values=1, axis=1 )
W

array([[1, 0, 3],
       [1, 1, 4],
       [1, 2, 1],
       [1, 3, 7]])

In [107]:
model = LinearRegression()

In [108]:
model.fit(W, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [109]:
print('intercept:', model.intercept_)

intercept: -1.2448979591836729


In [110]:
print('slope:', model.coef_)

slope: [0.         0.40816327 0.43537415]


In [111]:
r_sq = model.score(X, y)
print(r_sq)

-0.6766316503925834


In [129]:
x1 = np.array([0,1,2,3])
y = np.array([0,1,0,3])
x1

array([0, 1, 2, 3])

In [130]:
A1 = np.vstack([x1, np.ones(len(x))]).T
#A2 = np.vstack([x2, np.ones(len(x))]).T
#A1

In [133]:
m1,c = np.linalg.lstsq(A1, y, rcond=None)[0]

In [134]:
m1,c

(0.7999999999999998, -0.19999999999999946)

In [116]:
0,18

(0, 18)

In [117]:
from sklearn.linear_model import Ridge


alpha=1.0

X = np.array( [ [0,3], [1,2], [2,1], [3,0] ] )
y = np.array( [ 0, 1, 0, 3 ] )

#expand X by 1.0 column

X = np.insert(X, 0, values=1, axis=1 )
print(X)

model = Ridge(alpha=alpha, fit_intercept=False )
model.fit(X, y )

print("coef:", model.coef_);
print('intercept:', model.intercept_)

[[1 0 3]
 [1 1 2]
 [1 2 1]
 [1 3 0]]
coef: [ 0.17391304  0.62450593 -0.1027668 ]
intercept: 0.0
